- name: SonarCloud Scan
  uses: SonarSource/sonarqube-scan-action@v1
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    SONAR_HOST_URL: https://sonarcloud.io
  with:
    args: >
      -Dsonar.projectKey=CyrusCrystos_Time_Stamp_Project
      -Dsonar.organization=CyrusCrystos
      -Dsonar.sources=stamply
