name: SonarCloud Scan

on:
  push:
    branches:
      - main
      - True-Branch
  pull_request:
    branches:
      - main
      - True-Branch

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectKey: CyrusCrystos_Time_Stamp_Project
          organization: CyrusCrystos
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
